### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Gaurav7888**

### CODE REVIEW

**Comment by Blackcipher101** [comment]
You will try and have to integrate into the website and also try using git and better name of the pull request :smile:

**Review by Blackcipher101 — CHANGES_REQUESTED** [review]
integrate into the website

**Comment by Gaurav7888** [comment]
can u tell me which particular  file i need to add this function to integrate @Blackcipher101

**Comment by Blackcipher101** [comment]
> can u tell me which particular file i need to add this function to integrate @Blackcipher101

Adding it in views.py will make the needed changes but it wouldn't integrate but I can make another issue for it

**Comment by Gaurav7888** [comment]
ya plz make one more issue for integrate part @Blackcipher101

**Pull request closed without merging**
